config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       registrations: 'users/registrations' }

  root 'home#index'
  get 'slot'=>'home#slot'

  get 'users/:id' => 'users#show',:as=>:user

  resources :homeworks do
    get 'dashboard',on: :collection
    get 'chart',on: :member

    resources :have_homeworks do
      get 'dashboard',on: :collection
      post 'score',on: :member

    end
  end

end

app/models/have_homework.rb
class HaveHomework < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  belongs_to :homework, :class_name => "Homework", :foreign_key => "homework_id", :counter_cache => true


  def score_text
    if score==4
      'A+'
    elsif score==3
      'A'
    elsif score==2
      'A-'
    elsif score==1
      '遲交或未達基本標準'
    else
      '尚未評分'
    end
  end

end

app/controllers/have_homeworks_controller.rb
class HaveHomeworksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_homework
  before_action :check_exist_homework,:only=>[:new]
  authorize_resource

  def dashboard
    @have_homeworks=@homework.have_homeworks.where("score is NULL").page(params[:page]).per(10).order("have_homeworks.updated_at desc")
  end

  def new
    @have_homework=current_user.have_homeworks.new
  end

  def create
    @have_homework=current_user.have_homeworks.new(have_homework_params)
    @have_homework.homework_id=@homework.id
    @have_homework.last_submit_at=DateTime.now
    if @have_homework.save
      redirect_to homework_path(@homework)
    else
      render :new
    end
  end

  def edit
    @have_homework=current_user.have_homeworks.where(homework_id:@homework.id).first
  end

  def update
    @have_homework=current_user.have_homeworks.where(homework_id:@homework.id).first
    @have_homework.last_submit_at=DateTime.now
    if @have_homework.update(have_homework_params)
      redirect_to homework_path(@homework)
    else
      render :new
    end
  end

  def score
    @have_homework=@homework.have_homeworks.find(params[:id])
    @have_homework.score=params[:score]
    if   @have_homework.save
      flash[:info]="評分成功"
    else
      flash[:alert]=@have_homework.errors.full_messages
    end
    redirect_to dashboard_homework_have_homeworks_path(@homework)
  end

  private

  def find_homework
    @homework=Homework.find(params[:homework_id])
  end

  def check_exist_homework
    if current_user.write_homework?(@homework)
      @have_homework=current_user.have_homeworks.where(homework_id:@homework.id).first
      redirect_to edit_homework_have_homework_path(@homework,@have_homework)
    end

  end

  def have_homework_params
    params.require(:have_homework).permit(:repo_url)
  end
end

app/helpers/have_homeworks_helper.rb
module HaveHomeworksHelper

  def last_update(work)
    if work.last_submit_at.present?
      date_format(work.last_submit_at)
    else
      date_format(work.updated_at)
    end
  end

  def score_label(work)
    label_class="label "
    if work.score==4
      label_class+="label-primary"
    elsif work.score==3
      label_class+="label-success"
    elsif work.score==2
      label_class+="label-info"
    else
      label_class+="label-warning"
    end
    content_tag(:span,work.score_text,class:label_class)
  end
end

app/views/have_homeworks/_form.html.erb
<%= form_for [homework,have_homework] do |f| %>
<div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">作業repo url</label>
	<div class="col-sm-10">
		<%= f.text_field :repo_url,:class=>"form-control",:placeholder=>"作業repo url"%>  
	</div>
</div>


<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%=f.submit :save,:class=>"btn btn-default"%>  	
	</div>
</div>  
<% end %>

app/views/have_homeworks/dashboard.html.erb
<div>
	<p>	作業名稱: <%=@homework.name%>  </p>
<p>截止日期:<%=date_format(@homework.deadline)%>  </p>
	<div class="panel panel-default">
		<div class="panel-heading">作業說明</div>
		<div class="panel-body">
		<%=render_homework_content @homework%>
		</div>
	</div>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Repo url</th>
			<th>最後更新日期</th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>

		<%@have_homeworks.each do|work|%>
		<tr>
			<td><%= link_to work.user.name, user_path(work.user) %>   </td>
			<td><%= link_to work.repo_url, work.repo_url,target:"_blank" %>  </td>
			<td><%= date_format work.updated_at%>  </td>
			<td><%= link_to "A+", score_homework_have_homework_path(@homework,work,score:4),method:"post" %></td>
			<td><%= link_to "A", score_homework_have_homework_path(@homework,work,score:3),method:"post" %></td>
			<td><%= link_to "A-", score_homework_have_homework_path(@homework,work,score:2),method:"post" %></td>
			<td><%= link_to "遲交", score_homework_have_homework_path(@homework,work,score:1),method:"post" %></td>

		</tr>
		<%end%>
	</tbody>
</table>

<%= paginate @have_homeworks %>

app/views/have_homeworks/edit.html.erb
<h2>繳交作業</h2>

<%=render :partial =>"form", :locals => { homework:@homework,have_homework:@have_homework } %>

app/views/have_homeworks/new.html.erb
<h2>繳交作業</h2>

<%=render :partial =>"form", :locals => { homework:@homework,have_homework:@have_homework } %>