config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       registrations: 'users/registrations' }

  root 'home#index'
  get 'slot'=>'home#slot'

  get 'users/:id' => 'users#show',:as=>:user

  resources :homeworks do
    get 'dashboard',on: :collection
    get 'chart',on: :member

    resources :have_homeworks do
      get 'dashboard',on: :collection
      post 'score',on: :member

    end
  end

end

app/models/homework.rb
class Homework < ActiveRecord::Base
  has_many :have_homeworks

  def complete_work_count
    have_homeworks_count
  end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_homework,:only=>[:show,:edit,:update,:chart]
  authorize_resource

  def index
    @homeworks=Homework.all.order("id desc")
  end

  def dashboard
    @homeworks=Homework.all
  end

  def show
    @have_homeworks=@homework.have_homeworks.includes(:user).page(params[:page]).per(10).order("have_homeworks.updated_at desc")
  end

  def new
    @homework=Homework.new
  end

  def create
    @homework=Homework.new(homework_params)
    if @homework.save
      redirect_to homeworks_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @homework.update(homework_params)
      redirect_to homeworks_path
    else
      render :edit
    end
  end

  def chart
    scores=@homework.have_homeworks.select('score,count(id) as amount').group('score')
    @result=[0,0,0,0]
    scores.each do|score|
      @result[score["score"]-4]=score["amount"] if score["score"].present?
    end
  end


  private

  def homework_params
    params.require(:homework).permit(:name,:introduction,:deadline)
  end

  def find_homework
    @homework=Homework.find(params[:id])
  end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_for @homework do |f| %>
<div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">作業名稱</label>
	<div class="col-sm-10">
		<!-- <input type="email" class="form-control" id="inputEmail3" placeholder="Email"> -->
		<%= f.text_field :name,:class=>"form-control",:placeholder=>"作業名稱"%>  
	</div>
</div>
<div class="form-group">
	<label for="inputPassword3" class="col-sm-2 control-label">作業說明</label>
	<div class="col-sm-10">
		<!-- <input type="password" class="form-control" id="inputPassword3" placeholder="Password"> -->
		<!-- <textarea class="form-control" rows="3"></textarea> -->

		<%= f.text_area :introduction,:class=>"form-control",:placeholder=>"作業說明",
		:"data-provide"=>"markdown"%>  

	</div>
</div>

<div class="form-group">
	<label for="inputPassword3" class="col-sm-2 control-label">作業說明</label>
	<div class="col-sm-10">
		<!-- <input type="password" class="form-control" id="inputPassword3" placeholder="Password"> -->
		<!-- <textarea class="form-control" rows="3"></textarea> -->

		<%= f.text_field :deadline,:class=>"form-control",:placeholder=>"截止日期"%>  

	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%=f.submit :save,:class=>"btn btn-default"%>  	
	</div>
</div>
<% end %>

app/views/homeworks/chart.html.erb
<h2>成績排行</h2>

<canvas id="myChart" width="400" height="400"></canvas>
<script type="text/javascript">
	var data = {
    labels: ["A+", "A", "A-", "others"],
    datasets: [
 
        {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.5)",
            strokeColor: "rgba(151,187,205,0.8)",
            highlightFill: "rgba(151,187,205,0.75)",
            highlightStroke: "rgba(151,187,205,1)",
            data: <%=@result.to_json%>  
        }
    ]
};
	var ctx = document.getElementById("myChart").getContext("2d");
	var myBarChart = new Chart(ctx).Bar(data);

</script>

app/views/homeworks/dashboard.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>作業名稱</th>
      <th>截止日期</th>
      <th>完成人數</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%@homeworks.each do|homework|%>  
    <tr>
      <td><%= link_to homework.name, homework_path(homework) %>  </td>
      <td><%= date_format(homework.deadline)%>   </td>
      <td><%= homework.complete_work_count%>  </td>
      <% if can? :update,homework %>
      <td>
        <%= link_to "edit", edit_homework_path(homework) %>
      </td>
      <td>
        <%= link_to "批改作業", dashboard_homework_have_homeworks_path(homework) %>
      </td>
      <% end %>
    </tr>
    <%end%>  
    
  </tbody>
</table>

app/views/homeworks/edit.html.erb
<h2>edit homework</h2>

<%=render :partial =>"form", :locals => { homework:@homework } %>

app/views/homeworks/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>作業名稱</th>
      <th>截止日期</th>
      <th>完成人數</th>
      <th>成績排行</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%@homeworks.each do|homework|%>  
    <tr>
      <td><%= link_to homework.name, homework_path(homework) %>  </td>
      <td><%= date_format(homework.deadline)%>   </td>
      <td><%= homework.complete_work_count%>  </td>
      <td><%= link_to "成績排行", chart_homework_path(homework) %></td>
      <% if can? :update,homework %>
      <td>
        <%= link_to "edit", edit_homework_path(homework) %>

      </td>
      <% end %>
    </tr>
    <%end%>  
    
  </tbody>
</table>

app/views/homeworks/new.html.erb
<h2>new homework</h2>

app/views/homeworks/show.html.erb
<div>
	<p>	作業名稱: <%=@homework.name%>  </p>

	<div class="panel panel-default">
		<div class="panel-heading">作業說明</div>
		<div class="panel-body">
		<%=render_homework_content @homework%>
		</div>
	</div>
</div>


<%= link_to "繳交作業", new_homework_have_homework_path(@homework),class:"btn btn-default" %>
<% if can? :edit,@homework %>
	<%= link_to "編輯", edit_homework_path(@homework),class:"btn btn-success" %>
<% end %>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Repo url</th>
			<th>最後更新日期</th>
		</tr>
	</thead>
	<tbody>

		<%@have_homeworks.each do|work|%>
		<tr>
			<td><%= link_to work.user.name, user_path(work.user) %>  </td>
			<td><%= link_to work.repo_url, work.repo_url,target:"_blank" %>  </td>
			<td><%= last_update(work)%>  </td>
		</tr>
		<%end%>
	</tbody>
</table>

<%= paginate @have_homeworks %>