config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       registrations: 'users/registrations' }

  root 'home#index'
  get 'slot'=>'home#slot'

  get 'users/:id' => 'users#show',:as=>:user

  resources :homeworks do
    get 'dashboard',on: :collection
    get 'chart',on: :member

    resources :have_homeworks do
      get 'dashboard',on: :collection
      post 'score',on: :member

    end
  end

end

app/views/common/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Lucky Orange", root_path,:class=>"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "homeworks", homeworks_path %>
        </li>

        <li>
          <%= link_to "slot", slot_path %>
        </li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

        <% if can? :new,Homework %>
        
        <li><%= link_to "new homework", new_homework_path %></li>
        <li><%= link_to "改作業", dashboard_homeworks_path %></li>
        <% end %>
        <li> <%= link_to current_user.name, user_path(current_user) %></li>
        <li><%= link_to '編輯個人資訊', edit_user_registration_path %></li>

        <li> <%= link_to "log out", destroy_user_session_path,method:'delete' %></li>

        <% else %>

        <li> <%= link_to "login", user_omniauth_authorize_path(:github) %></li>
        <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>